name: Network Testing

on:
  push:
  workflow_dispatch:

jobs:
  network-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
    - name: Run main.sh
      run: bash main.sh
